% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Immunoassay (in Silico)},
  pdfauthor={Tianyi Shi},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs}
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{5}

\title{Immunoassay (in Silico)}
\author{Tianyi Shi}
\date{2020-03-08}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\hypertarget{aim-of-the-practical}{%
\section{Aim of the Practical}\label{aim-of-the-practical}}

\hypertarget{background}{%
\section{Background}\label{background}}

\hypertarget{q1}{%
\subsection*{Q1}\label{q1}}
\addcontentsline{toc}{subsection}{Q1}

Draw a simple schematic diagram of an IgG molecule, labelling the relevant chains and domains.

Diagram see Figure \ref{fig:ab-schematic}

\begin{figure}
\includegraphics[width=1\linewidth]{../img/ab-schematic} \caption{Schematic of an IgG molecule.}\label{fig:ab-schematic}
\end{figure}

\begin{enumerate}
\def\labelenumi{\roman{enumi}.}
\tightlist
\item
  What is meant by a polyclonal antibody?

  \begin{itemize}
  \tightlist
  \item
    A mixture of antibodies with diifferent F\textsubscript{v} regions (antigen-binding sites) that are complementary to different epitopes (on the same antigen)
  \end{itemize}
\item
  What is a monoclonal antibody?

  \begin{itemize}
  \tightlist
  \item
    A group of clone of a single antibody, with identical F\textsubscript{v} region and bind to the same epitope.
  \end{itemize}
\item
  Detail the steps by which mouse monoclonal antibodies are raised.

  \begin{itemize}
  \tightlist
  \item
    When the antigen molecules are injected (probably with an adjunvant e.g.~Aluminium salt to elicit immune response more effectively), they activate antigen-presenting cells (APCs) called dendritic cells. Activated dendritic cells then use their MHC class II to present antigens on their plasma membrane, while migrating to the lymphatic system. When they encounter B cells and T\textsubscript{h} (T helper) cells with cognate BCR/TCRs in lymph nodes, they activate these B and T cells. With the help from activated dendritic cells and T\textsubscript{h} cells, B cells undergoes monoclonal expansion, class switching and somatic hypermutation, and differentiate into plasma cells, which produce a large number of antibodies in a short period.
  \end{itemize}
\end{enumerate}

\hypertarget{introduction-to-radioimmunoassay}{%
\section{Introduction to Radioimmunoassay}\label{introduction-to-radioimmunoassay}}

\hypertarget{q2}{%
\subsubsection*{Q2}\label{q2}}
\addcontentsline{toc}{subsubsection}{Q2}

\textbf{18 tubes are set up for radioimmunoassay containing antibody with a capacity for binding 1µg antigen. Both labelled antigen and a known concentration of unlabelled antigen are added to the tube as indicated. Note that the labelled antigen has been conjugated with 125I so that approx 50,000 cpm are associated with every \(\mu\text{g}\) of labelled antigen). Fill in the table below giving values rounded to the nearest integer.}

\begin{longtable}[]{@{}rrrrrrr@{}}
\caption{Horizontal axis: unlabelled antigen (\(\mu\text{g}\)); vertical axis: labelled antigen (\(\mu\text{g}\));}\tabularnewline
\toprule
& 0 & 0.5 & 1 & 2 & 4 & 8\tabularnewline
\midrule
\endfirsthead
\toprule
& 0 & 0.5 & 1 & 2 & 4 & 8\tabularnewline
\midrule
\endhead
\textbf{0.5} & \emph{25000} & 25000 & 16667 & 10000 & 5556 & 2941\tabularnewline
\textbf{1.0} & 50000 & 33333 & 25000 & 16666 & 10000 & 5556\tabularnewline
\textbf{2.0} & 50000 & 40000 & 33333 & 25000 & 16667 & 10000\tabularnewline
\bottomrule
\end{longtable}

When the antibodies are saturated with antigens (when the amount of total antigen is greater than \(1 \mu\text{g}\)), the radioactivity is the proportion of labelled antigen multiplied by the maximal radioactivity (50000 cpm). There is one case (0 \(\mu\text{g}\) unlabelled; 0.5 \(\mu\text{g}\) labelled) where the antibodies are not saturated.

\hypertarget{q3}{%
\subsubsection*{Q3}\label{q3}}
\addcontentsline{toc}{subsubsection}{Q3}

\textbf{Use the data from Q2 to draw curves of \emph{counts precipitated} versus \emph{amount of unlabelled antigen} added at each concentration of labelled antigen.}

There are two ways to plot it. The obvious way is to directly plot the radioactivity count against the amount of unlabelled antigen (Figure \ref{fig:q2} \textbf{A}). However, by simply taking the reciprocal of the radioactivity count, a linear relationship can be obtained (Figure \ref{fig:q2} \textbf{B}). This is explained in more detail in Q4.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{# Loading data}
\NormalTok{d <-}\StringTok{ }\KeywordTok{tibble}\NormalTok{(}\DataTypeTok{labelled =} \KeywordTok{rep}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\StringTok{'0.5 microgram'}\NormalTok{, }\StringTok{'1 microgram'}\NormalTok{, }\StringTok{'2 microgram'}\NormalTok{), }\DataTypeTok{each =} \DecValTok{6}\NormalTok{),}
       \DataTypeTok{unlabelled =} \KeywordTok{rep}\NormalTok{(}\KeywordTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\FloatTok{0.5}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{8}\NormalTok{), }\DecValTok{3}\NormalTok{),}
       \DataTypeTok{count =} \KeywordTok{c}\NormalTok{(}\DecValTok{25000}\NormalTok{, }\DecValTok{25000}\NormalTok{, }\DecValTok{16667}\NormalTok{, }\DecValTok{10000}\NormalTok{, }\DecValTok{5556}\NormalTok{, }\DecValTok{2941}\NormalTok{,}
                 \DecValTok{50000}\NormalTok{, }\DecValTok{33333}\NormalTok{, }\DecValTok{25000}\NormalTok{, }\DecValTok{16666}\NormalTok{, }\DecValTok{10000}\NormalTok{, }\DecValTok{5556}\NormalTok{,}
                 \DecValTok{50000}\NormalTok{, }\DecValTok{40000}\NormalTok{, }\DecValTok{33333}\NormalTok{, }\DecValTok{25000}\NormalTok{, }\DecValTok{16667}\NormalTok{, }\DecValTok{10000}\NormalTok{))}
\CommentTok{# Direct plot}
\NormalTok{direct <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(d, }\KeywordTok{aes}\NormalTok{(unlabelled, count, }\DataTypeTok{linetype =}\NormalTok{ labelled))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_line}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title=}\StringTok{'Direct Plotting'}\NormalTok{)}
\CommentTok{# Plot after transformation}
\NormalTok{linear <-}\StringTok{ }\KeywordTok{ggplot}\NormalTok{(d, }\KeywordTok{aes}\NormalTok{(unlabelled, }\DecValTok{10000}\OperatorTok{/}\NormalTok{count, }\DataTypeTok{linetype =}\NormalTok{ labelled))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_line}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title=}\StringTok{"Tranformed to Linear Relationship"}\NormalTok{)}
\CommentTok{# Arrangement}
\KeywordTok{ggarrange}\NormalTok{(direct, linear, }\DataTypeTok{ncol=}\DecValTok{2}\NormalTok{, }\DataTypeTok{nrow=}\DecValTok{1}\NormalTok{, }\DataTypeTok{common.legend =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{legend=}\StringTok{"bottom"}\NormalTok{, }\DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{, }\StringTok{"B"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{2020-03-08-immunoassay-in-silico_files/figure-latex/q2-1} \caption{A: direct plotting; B: plotting the reciprocal of radioactivity count against unlabelled antigen amount.}\label{fig:q2}
\end{figure}

\hypertarget{q4}{%
\subsubsection*{Q4}\label{q4}}
\addcontentsline{toc}{subsubsection}{Q4}

\textbf{Explain why these curves have a negative slope.}

When antibodies are saturated with antigens, this simple relationship holds:

\[y=\dfrac{k}{x+k}\times A\]

where \(k\) is the amount of labelled antigen (constant), \(x\) is the amount of unlabelled antigen, \(A\) is the maximal radioactivity count (when \(x=0\) and all antibodies are bound to labelled antigens). In other words, the proportion of labelled antigen (relative to the total amount of antigen that saturates the antibodies) equals the ratio between the actual radioactivity and the maximal radioactivity. Thus, according to this equation, plotting radioactivity against amount of unlabelled antigen will result in a negative slope.

Taking the reciprocal results in a linear relationship between \(\dfrac{1}{y}\) and \(x\), and this was used to plot Q3 and later the calibration curve.

\[\dfrac{1}{y}=\dfrac{x}{Ak} + A\]

\hypertarget{q5}{%
\subsubsection*{Q5}\label{q5}}
\addcontentsline{toc}{subsubsection}{Q5}

\textbf{From the data in Q3 and Q4 and your graph, identify the range of counts precipitated that would be useful for calibration (i.e.~that will give you a significant change in counts precipitated when you add antigen).}

The slope of the curve is steeper (i.e.~it's more sensitive to small change in unlabelled antigen amount) as the radioactivity count is closer to maximum (50000). However, when the count is too close to 50000, the amount of unlabelled antigen would be too low, which would be more error-prone.

Thus my answer is: 5000-20000 cpm.

\hypertarget{q6}{%
\subsubsection*{Q6}\label{q6}}
\addcontentsline{toc}{subsubsection}{Q6}

\textbf{How does this vary with {[}Ag{]} labelled and {[}Ag{]} unlabelled?}

A decrease in {[}Ag{]}\textsubscript{labelled} increases the sensitivity of RIA for detecting {[}Ag{]}\textsubscript{unlabelled}, but the amount of labelled antigen must be at least as much as the capacity of the antibodies (in this case, 1 microgram), otherwise it would be impossible to detect very small amount (precisely, capacity of antibodies minus amount of labelled antigen) of unlabelled antigen.

As {[}Ag{]}\textsubscript{unlabelled} increases, the change in cpm becomes less significant.

\textbf{What does this tell you about the dynamic range of the assay (i.e.~the range of amounts of unlabelled antigen you can measure) in these particular experiments?}

The dynamic range varies with the amount of labelled antigen. Greater {[}Ag{]}\textsubscript{labelled} allows measurement of larger {[}Ag{]}\textsubscript{unlabelled} (but has less absolute precision/sensitivity); smaller {[}Ag{]}\textsubscript{labelled} allows more precise measurement of low concentrations of unlabelled antigen, but becomes insensitive when {[}Ag{]}\textsubscript{unlabelled} is high. The amount of labelled antigen must be at least as much as the capacity of the antibodies, as noted above.

\hypertarget{radioimmunoassay-simulation-tutorial}{%
\section{Radioimmunoassay Simulation --- Tutorial}\label{radioimmunoassay-simulation-tutorial}}

\hypertarget{a-choosing-a-suitable-concentration-of-ab}{%
\subsection*{(a) Choosing a suitable concentration of Ab}\label{a-choosing-a-suitable-concentration-of-ab}}
\addcontentsline{toc}{subsection}{(a) Choosing a suitable concentration of Ab}

\textbf{7. Enter your results in the table below, using scientific notation rather than strings of zeros.}

\begin{longtable}[]{@{}rrrrrr@{}}
\toprule
Tube & Ag dil & Ag vol (\(\mu\text{l}\)) & Ab dil (\(\mu\text{l}\)) & Ab vol & cpm\tabularnewline
\midrule
\endhead
1 & - & 0 & 10\textsuperscript{6} & 1 & 489\tabularnewline
2 & - & 0 & 10\textsuperscript{5} & 1 & 5525\tabularnewline
3 & - & 0 & 10\textsuperscript{4} & 1 & 44899\tabularnewline
4 & - & 0 & 10\textsuperscript{3} & 1 & 51875\tabularnewline
5 & - & 0 & 10\textsuperscript{2} & 1 & 48750\tabularnewline
6 & - & 0 & 10\textsuperscript{1} & 1 & 51700\tabularnewline
\bottomrule
\end{longtable}

\textbf{14. Fill out the table below using own your own data from the results screen, making sure you use scientific notation (ie NOT like the data table on screen). Calculate how much Ag you have added.}

\begin{longtable}[]{@{}rrrrrrr@{}}
\toprule
\begin{minipage}[b]{0.04\columnwidth}\raggedleft
Tube\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\raggedleft
Ag dil\strut
\end{minipage} & \begin{minipage}[b]{0.21\columnwidth}\raggedleft
Ag vol (\(\mu\text{l}\))\strut
\end{minipage} & \begin{minipage}[b]{0.16\columnwidth}\raggedleft
Amount of Ag (pg)\strut
\end{minipage} & \begin{minipage}[b]{0.21\columnwidth}\raggedleft
Ab dil (\(\mu\text{l}\))\strut
\end{minipage} & \begin{minipage}[b]{0.06\columnwidth}\raggedleft
Ab vol\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
cpm\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
10\textsuperscript{3}\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
1000\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
10\textsuperscript{6}\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
\textbf{4606}\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
7\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
700\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
10\textsuperscript{5}\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
\textbf{5178}\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
3\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
5\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
700\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
\textbf{9203}\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
4\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
100\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
10\textsuperscript{3}\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
\textbf{25687}\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
5\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
10\textsuperscript{5}\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.16\columnwidth}\raggedleft
10\strut
\end{minipage} & \begin{minipage}[t]{0.21\columnwidth}\raggedleft
10\textsuperscript{2}\strut
\end{minipage} & \begin{minipage}[t]{0.06\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
\textbf{51613}\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\textbf{Unique Code: txt9}

\hypertarget{b-testing-effect-of-changing-ab-at-fixed-ag}{%
\subsection*{(b) Testing effect of changing {[}Ab{]} at fixed {[}Ag{]}}\label{b-testing-effect-of-changing-ab-at-fixed-ag}}
\addcontentsline{toc}{subsection}{(b) Testing effect of changing {[}Ab{]} at fixed {[}Ag{]}}

\textbf{2. Increase the Ab concentration 10x (ie decrease the dilution factor to 103) and test against three concentrations of Ag (diluted 10\textsuperscript{3}, 10\textsuperscript{4} and 10\textsuperscript{5}) (Keep volume of Ab and Ag at 1 \(\mu\text{l}\) for now). Click Experiment and 1mg/ml to generate data. Enter the results.}

\begin{longtable}[]{@{}rrrrrrr@{}}
\toprule
\begin{minipage}[b]{0.04\columnwidth}\raggedleft
Tube\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Ag vol (\(\mu\text{l}\))\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Ag dil'n\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\raggedleft
Ag mass (pg)\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Ab dil'n\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Ab vol (\(\mu\text{l}\))\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\raggedleft
cpm\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{3}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
1000\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{3}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
48772\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
100\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{3}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
55150\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
3\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{5}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
10\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{3}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
43975\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\textbf{3. Now perform the same experiment but with the `optimal' Ab dilution of 10\textsuperscript{4}.}

\begin{longtable}[]{@{}rrrrrrr@{}}
\toprule
\begin{minipage}[b]{0.04\columnwidth}\raggedleft
Tube\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Ag vol (\(\mu\text{l}\))\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Ag dil'n\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\raggedleft
Ag mass (pg)\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Ab dil'n\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Ab vol (\(\mu\text{l}\))\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\raggedleft
cpm\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{3}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
1000\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
4122\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
100\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
22237\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
3\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{5}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
10\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
44681\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\textbf{4. Finally, set up three tubes with 10x LESS Ab than the `optimal' i.e.~diluted 10\textsuperscript{5}. Again, note your data:}

\begin{longtable}[]{@{}rrrrrrr@{}}
\toprule
\begin{minipage}[b]{0.04\columnwidth}\raggedleft
Tube\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Ag vol (\(\mu\text{l}\))\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Ag dil'n\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\raggedleft
Ag mass (pg)\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Ab dil'n\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Ab vol (\(\mu\text{l}\))\strut
\end{minipage} & \begin{minipage}[b]{0.04\columnwidth}\raggedleft
cpm\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{3}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
1000\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{5}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\raggedleft
402\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
100\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{5}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\raggedleft
2366\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
3\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{5}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
10\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{5}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.04\columnwidth}\raggedleft
4872\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{q6-1}{%
\subsubsection*{Q6}\label{q6-1}}
\addcontentsline{toc}{subsubsection}{Q6}

\textbf{How does the amount of antibody influence the number of counts precipitated?}

The number of counts increases with increasing antibody concentration until the antigen-binding capacity of antibodies exceed the amount of labelled antigen (when Ab dilution is 10\textsuperscript{3}). In this case, additional unlabelled antigens will just bind free antibodies without interfering with those bound to labelled antigens.

\hypertarget{q7}{%
\subsubsection*{Q7}\label{q7}}
\addcontentsline{toc}{subsubsection}{Q7}

See Figure \ref{fig:immunolab-q7}.

\begin{figure}
\includegraphics[width=1\linewidth]{../img/immunolab-q7} \caption{Q7}\label{fig:immunolab-q7}
\end{figure}

\hypertarget{d-testing-precision}{%
\subsection*{(d) Testing precision}\label{d-testing-precision}}
\addcontentsline{toc}{subsection}{(d) Testing precision}

\begin{longtable}[]{@{}rrrrrrr@{}}
\toprule
\begin{minipage}[b]{0.04\columnwidth}\raggedleft
Tube\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Ag vol (\(\mu\text{l}\))\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Ag dil'n\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\raggedleft
Ag mass (pg)\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Ab dil'n\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Ab vol (\(\mu\text{l}\))\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\raggedleft
cpm\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
200\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
19215\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
200\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
14307\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
3\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
200\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
14866\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
4\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
200\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
14474\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
5\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
200\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
14607\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
6\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
200\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
15341\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
7\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
-\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
51798\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
8\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
-\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
45749\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
9\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
-\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
52873\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
10\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
-\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
55798\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
11\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
-\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
57048\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
12\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
-\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
0\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
49474\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\hypertarget{q8}{%
\subsubsection*{Q8}\label{q8}}
\addcontentsline{toc}{subsubsection}{Q8}

See Figure \ref{fig:immunolab-q8}

\begin{figure}
\includegraphics[width=1\linewidth]{../img/immunolab-q8} \caption{Q8}\label{fig:immunolab-q8}
\end{figure}

\hypertarget{q9}{%
\subsubsection*{Q9}\label{q9}}
\addcontentsline{toc}{subsubsection}{Q9}

Calculations see Figure \ref{fig:immunolab-q9}

\begin{figure}
\includegraphics[width=1\linewidth]{../img/immunolab-q9} \caption{Q9}\label{fig:immunolab-q9}
\end{figure}

\textbf{Explain the possible causes of the variation, bearing in mind the experiments have been carried out by an experienced operator}

\begin{itemize}
\tightlist
\item
  Radioactive decay is a probablistic event, so the number of disintegrations per unit time naturally varies.
\item
  There can also be random errors intrintic to the Geiger counter
\end{itemize}

\hypertarget{ria-generating-your-own-data}{%
\section{RIA: Generating Your Own Data}\label{ria-generating-your-own-data}}

\textbf{Unique Code:} \texttt{yckmq9fe}

\hypertarget{a-finding-a-suitable-concentration-of-antibody}{%
\subsection*{(a) Finding a suitable concentration of antibody}\label{a-finding-a-suitable-concentration-of-antibody}}
\addcontentsline{toc}{subsection}{(a) Finding a suitable concentration of antibody}

\textbf{4. Using the grid below\ldots{}}

See Figure \ref{fig:immunolab-5a4}

\begin{figure}
\includegraphics[width=1\linewidth]{../img/immunolab-5a4} \caption{5 (a) 4.}\label{fig:immunolab-5a4}
\end{figure}

\textbf{6. Note down useful data in the tables below}

\begin{longtable}[]{@{}rrrrrrr@{}}
\toprule
\begin{minipage}[b]{0.04\columnwidth}\raggedleft
Tube\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Ag vol (\(\mu\text{l}\))\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Ag dil'n\strut
\end{minipage} & \begin{minipage}[b]{0.12\columnwidth}\raggedleft
Ag mass (pg)\strut
\end{minipage} & \begin{minipage}[b]{0.08\columnwidth}\raggedleft
Ab dil'n\strut
\end{minipage} & \begin{minipage}[b]{0.22\columnwidth}\raggedleft
Ab vol (\(\mu\text{l}\))\strut
\end{minipage} & \begin{minipage}[b]{0.05\columnwidth}\raggedleft
cpm\strut
\end{minipage}\tabularnewline
\midrule
\endhead
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{2}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
346\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
2\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{3}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
10\textsuperscript{3}\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
4083\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
3\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
10\textsuperscript{2}\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
18380\strut
\end{minipage}\tabularnewline
\begin{minipage}[t]{0.04\columnwidth}\raggedleft
4\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{5}\strut
\end{minipage} & \begin{minipage}[t]{0.12\columnwidth}\raggedleft
10\strut
\end{minipage} & \begin{minipage}[t]{0.08\columnwidth}\raggedleft
10\textsuperscript{4}\strut
\end{minipage} & \begin{minipage}[t]{0.22\columnwidth}\raggedleft
1\strut
\end{minipage} & \begin{minipage}[t]{0.05\columnwidth}\raggedleft
35217\strut
\end{minipage}\tabularnewline
\bottomrule
\end{longtable}

\textbf{8. If necessary, try varying the volume at given Ab dilution to see if you can optimise further.}

I decided to use the 10\textsuperscript{4} dilution.

\hypertarget{b-generating-the-calibartion-curve-and-c-finding-the-concentration-of-the-unknown}{%
\subsection*{(b) Generating the calibartion curve and (c) Finding the concentration of the unknown}\label{b-generating-the-calibartion-curve-and-c-finding-the-concentration-of-the-unknown}}
\addcontentsline{toc}{subsection}{(b) Generating the calibartion curve and (c) Finding the concentration of the unknown}

\textbf{5. Note all the relevant data in the table below}

Implicitly shown in Figure \ref{fig:ria-cali-raw} and \ref{fig:ria-cali}.

\textbf{Q10: How many replicates would be appropriate for your unknown solution? Explain your answer using sound statistical reasoning.}

This depends on the precision we want to achieve, the \emph{p} value we adopt, and the variance of the results of the repeats of that particular piece of experiment (which is unknown before we have done them). For example, if we choose \(p=0.05\) as the threshold, and did some experiments resulting in a mean of \(\bar{x}\) and standard deviation of \(s_x\), the confidence interval of the population mean, \(\mu\), will be:

\[\mu = \bar{x} \pm t_{0.975, n} \times \dfrac{s_x}{\sqrt{n}}\]

Clearly, in order to calculate \(n\), it should be specified clearly to what precision we want to achieve for \(\mu\), and calculate \(\mu\) each time we finish one repeat of the experiment (because \(\bar{x}\) and \(s_x\) will update).

\textbf{You may have to test a range of Ag dilutions before you obtain a cpm value that can be read of your calibration curve (remember to find appropriate range first by altering only the dilution). Show your preliminary data here:}

\begin{longtable}[]{@{}rrr@{}}
\toprule
Unknown Ag dilution & Unknown Ag volume (\(\mu\text{l}\)) & cpm\tabularnewline
\midrule
\endhead
10\textsuperscript{2} & 1 & 454\tabularnewline
10\textsuperscript{3} & 5 & 826\tabularnewline
10\textsuperscript{3} & 1 & 3857\tabularnewline
10\textsuperscript{4} & 5 & 8245\tabularnewline
\textbf{10\textsuperscript{4}} & \textbf{1} & \textbf{19760}\tabularnewline
10\textsuperscript{5} & 5 & 29922\tabularnewline
10\textsuperscript{5} & 1 & 33886\tabularnewline
\bottomrule
\end{longtable}

I decide to use Ag dilution of 10\textsuperscript{4} and volume of 1 \(\mu\text{l}\), because 19760 is within the optimal range of the calibration curve (shown later, as a response to Q11)

\textbf{Q11: Read the data off your calibration curve, and calculate the concentration of antigen in your unknown solution. (Each successful measurement will generate a value for the amount of antigen estimated to be present in that particular assay tube. You are required to calculate the concentration of antigen in the unknown solution). Explain your result below. Provide a discussion of your experimental approach, the validity of your answer (conduct appropriate statistical tests) and discuss any aspects that could have been improved. How would you express the precision of your answer (see Q.8)?}

Here I load the data (and standardised variable names):

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{library}\NormalTok{(tidyverse)}
\NormalTok{raw <-}\StringTok{ }\KeywordTok{read_tsv}\NormalTok{(}\StringTok{'./2020-03-08-immunoassay-in-silico/ria.tsv'}\NormalTok{) }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{transmute}\NormalTok{(}\DataTypeTok{antigen_volume =} \StringTok{`}\DataTypeTok{Ag volume}\StringTok{`}\NormalTok{,}
            \DataTypeTok{antigen_dilution =} \StringTok{`}\DataTypeTok{Ag dilution}\StringTok{`}\NormalTok{,}
            \DataTypeTok{antibody_volume =} \StringTok{`}\DataTypeTok{Ab volume}\StringTok{`}\NormalTok{,}
            \DataTypeTok{antibody_dilution =} \KeywordTok{factor}\NormalTok{(}\StringTok{`}\DataTypeTok{Ab dilution}\StringTok{`}\NormalTok{),}
            \DataTypeTok{count =}\NormalTok{ Count,}
            \DataTypeTok{known =} \StringTok{`}\DataTypeTok{Known?}\StringTok{`}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{calibration-curve}{%
\subsubsection*{Calibration Curve}\label{calibration-curve}}
\addcontentsline{toc}{subsubsection}{Calibration Curve}

\hypertarget{tidying-data}{%
\paragraph{Tidying data}\label{tidying-data}}
\addcontentsline{toc}{paragraph}{Tidying data}

I extracted experiments with known amount of antigen and calculated the mass of antigen in pg:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{known <-}\StringTok{ }\NormalTok{raw }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(known }\OperatorTok{==}\StringTok{ }\DecValTok{1}\NormalTok{, }\CommentTok{# experiments with known antigen amount for calibration}
\NormalTok{         antibody_dilution }\OperatorTok{==}\StringTok{ }\DecValTok{10000}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{antigen_amount =} 
\NormalTok{        antigen_volume }\OperatorTok{/}\StringTok{ }\DecValTok{1000} \CommentTok{# \textbackslash{}mu L to ml}
                       \OperatorTok{*}\StringTok{ }\DecValTok{10}\OperatorTok{^}\DecValTok{9}  \CommentTok{# mg to pg}
                       \OperatorTok{/}\StringTok{ }\NormalTok{antigen_dilution) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(antigen_amount}\OperatorTok{<=}\DecValTok{1000}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\hypertarget{plotting}{%
\paragraph{Plotting}\label{plotting}}
\addcontentsline{toc}{paragraph}{Plotting}

First, I plotted count vs antigen amount directly (the blue line is fitted using the LOESS algorithm) in Figure \ref{fig:ria-cali-raw} . Although this plot is not the most useful for calibration, it shows that the random variation is large when the count is greater than 20000. Therefore I aim at a count around 20000 in the test for the unkown antigen concentration.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{known }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(antigen_amount, count))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{span=}\FloatTok{0.9}\NormalTok{, }\DataTypeTok{se=}\OtherTok{FALSE}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{'antigen amount (pg)'}\NormalTok{, }\DataTypeTok{title =} \StringTok{'Calibration Curve (cpm vs antigen amount)'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\includegraphics{2020-03-08-immunoassay-in-silico_files/figure-latex/ria-cali-raw-1.pdf}
\caption{\label{fig:ria-cali-raw}RIA Calibration Curve}
\end{figure}

The real calibration curve is shown in Figure \ref{fig:ria-cali} (The reasoning was described in Q3 and Q4).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{known }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(antigen_amount, }\DecValTok{10000}\OperatorTok{/}\NormalTok{count))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{span=}\FloatTok{0.9}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{x =} \StringTok{'antigen amount (pg)'}\NormalTok{, }\DataTypeTok{title =} \StringTok{'Calibration Curve (10000/cpm vs antigen amount)'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\centering
\includegraphics{2020-03-08-immunoassay-in-silico_files/figure-latex/ria-cali-1.pdf}
\caption{\label{fig:ria-cali}RIA Calibration Curve (10000/count vs antigen amount)}
\end{figure}

The equation of the fitted straight line can be calculated as follows:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{with}\NormalTok{(known, }\KeywordTok{summary}\NormalTok{(}\KeywordTok{lm}\NormalTok{(}\DecValTok{10000}\OperatorTok{/}\NormalTok{count }\OperatorTok{~}\StringTok{ }\NormalTok{antigen_amount)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = 10000/count ~ antigen_amount)
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.33043 -0.05604  0.00116  0.05493  0.39587 
## 
## Coefficients:
##                 Estimate Std. Error t value Pr(>|t|)    
## (Intercept)    2.591e-01  1.659e-02   15.62   <2e-16 ***
## antigen_amount 2.486e-03  3.819e-05   65.10   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.133 on 134 degrees of freedom
## Multiple R-squared:  0.9693, Adjusted R-squared:  0.9691 
## F-statistic:  4238 on 1 and 134 DF,  p-value: < 2.2e-16
\end{verbatim}

This gives:

\[10000/\text{cpm} = 0.2591 + 2.486\times10^{-3}\text{antigen amount}\]

or:

\[\text{antigen amount (in pg)}=4022526/\text{cpm} - 104.2237\]

\hypertarget{testing-for-the-unkown}{%
\subsubsection*{Testing for the Unkown}\label{testing-for-the-unkown}}
\addcontentsline{toc}{subsubsection}{Testing for the Unkown}

Here is the data when I tried different antigen dilution and volumes to make the count close to 20000. \(1\mu\text{L}\) of \(1\times10^4\) dilution suffices:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{unknown_trial <-}\StringTok{ }\NormalTok{raw }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\StringTok{`}\DataTypeTok{known}\StringTok{`}\OperatorTok{==}\StringTok{ }\DecValTok{0}\NormalTok{,}
         \StringTok{`}\DataTypeTok{antigen_volume}\StringTok{`} \OperatorTok{!=}\StringTok{ }\DecValTok{0}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{slice}\NormalTok{(}\DecValTok{1}\OperatorTok{:}\DecValTok{7}\NormalTok{)}
\NormalTok{unknown_trial}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 7 x 6
##   antigen_volume antigen_dilution antibody_volume antibody_diluti~
##            <dbl>            <dbl>           <dbl> <fct>           
## 1              1              100               1 10000           
## 2              5             1000               1 10000           
## 3              1             1000               1 10000           
## 4              5            10000               1 10000           
## 5              1            10000               1 10000           
## 6              5           100000               1 10000           
## 7              1           100000               1 10000           
## # ... with 2 more variables: count <dbl>, known <dbl>
\end{verbatim}

Then I repeated \(1\mu\text{L}\) of \(1\times10^4\) dilution 276 times.\textbf{Curiously, the counts do not follow a normal distribution. It is bimodal:}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{unknown_test <-}\StringTok{ }\NormalTok{raw }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{filter}\NormalTok{(}\StringTok{`}\DataTypeTok{known}\StringTok{`}\OperatorTok{==}\StringTok{ }\DecValTok{0}\NormalTok{,}
         \StringTok{`}\DataTypeTok{antigen_volume}\StringTok{`} \OperatorTok{!=}\StringTok{ }\DecValTok{0}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{slice}\NormalTok{(}\DecValTok{8}\OperatorTok{:}\KeywordTok{n}\NormalTok{())}
\NormalTok{unknown_test }\OperatorTok{%>%}\StringTok{ }
\StringTok{  }\KeywordTok{ggplot}\NormalTok{(}\KeywordTok{aes}\NormalTok{(count))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_histogram}\NormalTok{(}\DataTypeTok{bins =} \DecValTok{40}\NormalTok{, }\DataTypeTok{fill=}\StringTok{'white'}\NormalTok{, }\DataTypeTok{color=}\StringTok{'black'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{'Distribution of 276 Radioactivity Count Readings'}\NormalTok{, }\DataTypeTok{x=}\StringTok{'radioactivity count'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{theme_bw}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\includegraphics{2020-03-08-immunoassay-in-silico_files/figure-latex/unnamed-chunk-5-1.pdf}

\textbf{This is likely to be a bug in the ImmunoLab application. }

If I had to assume it's a normal distribution, a 95\% confidence interval could be calculated:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{cpm =}\StringTok{ }\NormalTok{unknown_test[[}\StringTok{'count'}\NormalTok{]]}
\NormalTok{mass =}\StringTok{ }\DecValTok{4022526}\OperatorTok{/}\NormalTok{cpm }\OperatorTok{-}\StringTok{ }\FloatTok{104.2237}
\NormalTok{conc =}\StringTok{ }\NormalTok{mass }\OperatorTok{/}
\StringTok{          }\FloatTok{1e-3} \OperatorTok{/}\StringTok{ }\CommentTok{# 1e-3 ml}
\StringTok{          }\FloatTok{1e-4} \OperatorTok{/}\StringTok{ }\CommentTok{# dilution}
\StringTok{          }\FloatTok{1e9}  \CommentTok{# pg to mg}
\NormalTok{mean =}\StringTok{ }\KeywordTok{mean}\NormalTok{(conc); sd =}\StringTok{ }\KeywordTok{sd}\NormalTok{(conc);}
\NormalTok{t =}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\KeywordTok{length}\NormalTok{(conc)}\OperatorTok{-}\DecValTok{1}\NormalTok{); t_sd =}\StringTok{ }\NormalTok{t}\OperatorTok{*}\NormalTok{sd}
\KeywordTok{c}\NormalTok{(}\DataTypeTok{mean=}\NormalTok{mean, }\DataTypeTok{sd =}\NormalTok{ sd, }\DataTypeTok{t =}\NormalTok{ t, }\DataTypeTok{t_sd =}\NormalTok{ t_sd, }\DataTypeTok{lower =}\NormalTok{ mean}\OperatorTok{-}\NormalTok{t_sd, }\DataTypeTok{upper =}\NormalTok{ mean}\OperatorTok{+}\NormalTok{t_sd)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##      mean        sd         t      t_sd     lower     upper 
## 0.8361621 0.1897999 1.9686279 0.3736453 0.4625168 1.2098075
\end{verbatim}

(The relationship between cpm and antigen amount has been established previously: \(\text{antigen amount (in pg)}=4022526/\text{cpm} - 104.2237\))

The mean is 0.8362 mg/ml and the confidence interval is \(0.8362\pm0.3736\), or {[}0.4625 1.2098{]} mg/ml. (This is actually invalid because the distribution was not normal).

\hypertarget{enzyme-linked-immunosorbentassay}{%
\section{Enzyme-Linked Immunosorbentassay}\label{enzyme-linked-immunosorbentassay}}

\hypertarget{a-background-to-elisa}{%
\subsection*{(a) Background to ELISA}\label{a-background-to-elisa}}
\addcontentsline{toc}{subsection}{(a) Background to ELISA}

\hypertarget{q12}{%
\subsubsection*{Q12}\label{q12}}
\addcontentsline{toc}{subsubsection}{Q12}

\textbf{Draw a simple labelled diagram showing the principle of a sandwich ELISA.}

See Figure \ref{fig:immunolab-elisa}.

\begin{figure}
\includegraphics[width=1\linewidth]{../img/immunolab-elisa} \caption{Schematic of ELISA}\label{fig:immunolab-elisa}
\end{figure}

\hypertarget{q13}{%
\subsubsection*{Q13}\label{q13}}
\addcontentsline{toc}{subsubsection}{Q13}

\textbf{Give an example of a chromogenic substrate for:}

\begin{enumerate}
\def\labelenumi{(\roman{enumi})}
\tightlist
\item
  phosphatase: BCIP/NBT
\item
  peroxidase: TMB (3,3',5,5'-tetramethylbenzidine)
\end{enumerate}

\hypertarget{q14}{%
\subsubsection*{Q14}\label{q14}}
\addcontentsline{toc}{subsubsection}{Q14}

\textbf{Measuring the amount of enzyme in a well is technically simpler than measuring radioactivity, but it is much more susceptible to outside influences. List the factors that might affect the accuracy of your estimation of the amount of enzyme (assuming that optical density measurements are completely accurate).}

\begin{itemize}
\tightlist
\item
  Variation in temperature and pH
\item
  Aggregation of enzyme proteins (which leads to underestimation)
\end{itemize}

\hypertarget{b-method-elisalab}{%
\subsection*{(b) METHOD: ElisaLab}\label{b-method-elisalab}}
\addcontentsline{toc}{subsection}{(b) METHOD: ElisaLab}

\hypertarget{q15}{%
\subsubsection*{Q15}\label{q15}}
\addcontentsline{toc}{subsubsection}{Q15}

\textbf{What is the Beer-Lambert law and why is it relevant when working out how much labelled antibody to use?}

Beer-Lambert Law is:

\[A = \epsilon cl\]

where \(A\) is the absorbance (\(A=\log_{10}\left(\dfrac{I_\text{incident}}{I_\text{transmitted}}\right)\)), \(\epsilon\) is the molar extinction coefficient, \(c\) is the concentration of the light-absorbing substance, \(l\) is the path length.

By measuring absorbance (\(A\)), the concentration of the coloured product, and hence the concentration of the enzyme-conjugated antibodies, can be deduced.

\textbf{What would happen to the dynamic range if we used more labelled Ab?}

\hypertarget{etut}{%
\section{ELISA Tutorial}\label{etut}}

As I will be plot several heatmaps to show the ELISA results, and the procedures are similar, I created this helper function to prevent repetition:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{plot_elisa <-}\StringTok{ }\ControlFlowTok{function}\NormalTok{(fn, title) \{}
\NormalTok{  df <-}\StringTok{ }\KeywordTok{read_tsv}\NormalTok{(fn) }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\NormalTok{janitor}\OperatorTok{::}\KeywordTok{clean_names}\NormalTok{() }\OperatorTok{%>%}\StringTok{ }
\StringTok{    }\KeywordTok{mutate}\NormalTok{(}\DataTypeTok{ag_dilution =} \KeywordTok{factor}\NormalTok{(ag_dilution),}
           \DataTypeTok{ab_dilution =} \KeywordTok{factor}\NormalTok{(ab_dilution))}
  \KeywordTok{return}\NormalTok{(}\KeywordTok{ggplot}\NormalTok{(df, }\KeywordTok{aes}\NormalTok{(ab_dilution, ag_dilution, }\DataTypeTok{fill=}\NormalTok{absorbance))}\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_tile}\NormalTok{()}\OperatorTok{+}
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =}\NormalTok{ title)}\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_y_discrete}\NormalTok{(}\DataTypeTok{limits =} \KeywordTok{rev}\NormalTok{(}\KeywordTok{levels}\NormalTok{(df}\OperatorTok{$}\NormalTok{ag_dilution)))}\OperatorTok{+}
\StringTok{    }\KeywordTok{scale_fill_gradient}\NormalTok{(}\DataTypeTok{high=}\StringTok{'blue'}\NormalTok{, }\DataTypeTok{low=}\StringTok{'white'}\NormalTok{)}\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_text}\NormalTok{(}\KeywordTok{aes}\NormalTok{(}\DataTypeTok{label=}\NormalTok{absorbance)))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\textbf{\emph{A small flaw: until now I haven't found an easy way to show exponent forms of axes values in this case. It would have been straightforward if my axes had been continuous. However, heatmaps require discrete variables so I converted numerical values (continuous) to factors (discrete).}}

The results of the ELISA tutorial are shown in Figure \ref{fig:elisa-tut}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot_elisa}\NormalTok{(}\StringTok{'./2020-03-08-immunoassay-in-silico/elisa_tutorial.tsv'}\NormalTok{, }\StringTok{"ELISA Tutorial"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{2020-03-08-immunoassay-in-silico_files/figure-latex/elisa-tut-1} \caption{ELISA tutorial results}\label{fig:elisa-tut}
\end{figure}

\hypertarget{elisa-experiment}{%
\section{ELISA Experiment}\label{elisa-experiment}}

\textbf{Reference number:} \texttt{2nf5rpcd}

\hypertarget{a-choosing-a-suitable-concentration-of-antibody}{%
\subsection*{(a) Choosing a suitable concentration of antibody}\label{a-choosing-a-suitable-concentration-of-antibody}}
\addcontentsline{toc}{subsection}{(a) Choosing a suitable concentration of antibody}

\hypertarget{q16}{%
\subsubsection*{Q16}\label{q16}}
\addcontentsline{toc}{subsubsection}{Q16}

\textbf{Describe the steps you took to optimise Antibody dilution for the rest of the experiment.}

First, I used a wide range of antibody dilutions (but with smaller intervals around \(10^4\), as the optimal concentration is more likely to be around here), these concentrations are \(10^2, 10^3, 4\times10^3, 10^4, 4\times10^4, 8\times10^4, 10^5, 10^6\). The antigen concentrations are evenly distributed, namely \(1\times10^n\) and \(4\times10^n\) for \(n\) in \(\{1,2,3,4,5,6\}\). The results are shown in Figure \ref{fig:elisa-t1}. The \texttt{plot\_elisa()} function used here were defined in Section \ref{etut}. I believe the plots I made are a better representation of ELISA results than screenshots or Excel spreadsheets. However, if you wish to view the raw data, you can download them from \url{http://tianyishi2001.github.io/ox/lab/2020-03-08-immunoassay-in-silico/}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{plot_elisa}\NormalTok{(}\StringTok{'./2020-03-08-immunoassay-in-silico/elisa_trial_1.tsv'}\NormalTok{, }\StringTok{"ELISA Trial 1 (choosing antibody concentration)"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{2020-03-08-immunoassay-in-silico_files/figure-latex/elisa-t1-1} \caption{ELISA Trial 1 (choosing antibody concentration) results.}\label{fig:elisa-t1}
\end{figure}

As shown in Figure \ref{fig:elisa-t1}, the optimal antibody concentration is between \(4\times10^4\) and \(8\times10^4\). So in the next round of trial, I chosed antibody concentrations of \(3.2\times10^4\), \(4.0\times10^4\), \(6.4\times10^4\), and \(8.0\times10^4\). The antigen concentrations are the same as the previous trial. The experiments on these four antibody concentrations are repeated to fill 96 wells. The results are shown in Figure \ref{fig:elisa-t2}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{elisa_trial_}\DecValTok{2}\NormalTok{_}\DecValTok{1}\NormalTok{ <-}\StringTok{ }\KeywordTok{plot_elisa}\NormalTok{(}\StringTok{'./2020-03-08-immunoassay-in-silico/elisa_trial_2_1.tsv'}\NormalTok{, }\StringTok{"ELISA Trial 2-1"}\NormalTok{)}
\NormalTok{elisa_trial_}\DecValTok{2}\NormalTok{_}\DecValTok{2}\NormalTok{ <-}\StringTok{ }\KeywordTok{plot_elisa}\NormalTok{(}\StringTok{'./2020-03-08-immunoassay-in-silico/elisa_trial_2_2.tsv'}\NormalTok{, }\StringTok{"ELISA Trial 2-2"}\NormalTok{)}
\KeywordTok{ggarrange}\NormalTok{(elisa_trial_}\DecValTok{2}\NormalTok{_}\DecValTok{1}\NormalTok{, elisa_trial_}\DecValTok{2}\NormalTok{_}\DecValTok{2}\NormalTok{, }\DataTypeTok{ncol=}\DecValTok{2}\NormalTok{, }\DataTypeTok{nrow=}\DecValTok{1}\NormalTok{, }\DataTypeTok{common.legend =} \OtherTok{TRUE}\NormalTok{, }\DataTypeTok{legend=}\StringTok{"bottom"}\NormalTok{, }\DataTypeTok{labels =} \KeywordTok{c}\NormalTok{(}\StringTok{"A"}\NormalTok{, }\StringTok{"B"}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{2020-03-08-immunoassay-in-silico_files/figure-latex/elisa-t2-1} \caption{ELISA Trial 2 (choosing antibody concentration) results.}\label{fig:elisa-t2}
\end{figure}

The plot suggests that an antibody concentration of \(4.0\times10^4\) would be optimal. Its maximum is close to, but does not exceed, 2.0.

\hypertarget{b-generating-the-calibration-curve}{%
\subsection*{(b) Generating the calibration curve}\label{b-generating-the-calibration-curve}}
\addcontentsline{toc}{subsection}{(b) Generating the calibration curve}

\hypertarget{q17}{%
\subsubsection*{Q17}\label{q17}}
\addcontentsline{toc}{subsubsection}{Q17}

\textbf{Discuss how you generated data for your calibration curve (you can append titled data sets to the end of this document)}

\hypertarget{q18}{%
\subsubsection*{Q18}\label{q18}}
\addcontentsline{toc}{subsubsection}{Q18}

\textbf{Plot your results to generate a calibration curve. Ensure axes are labelled, amount (not dilution) of antigen is plotted and that you have provided a descriptive title of the graph.}

First, I used the same antigen concentrations as in previous two trials (\(1\times10^n\) and \(4\times10^n\) for \(n\) in \(\{1,2,3,4,5,6\}\).), as shown below (this code reads data into dataframe \texttt{std1} while printing unique dilutions used).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{std1 <-}\StringTok{ }\KeywordTok{read_tsv}\NormalTok{(}\StringTok{'./2020-03-08-immunoassay-in-silico/elisa_std1.tsv'}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{janitor}\OperatorTok{::}\KeywordTok{clean_names}\NormalTok{() }\OperatorTok{%T>%}
\StringTok{  }\CommentTok{# print dilutions used}
\StringTok{  }\NormalTok{(}\ControlFlowTok{function}\NormalTok{(d)\{}\KeywordTok{print}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\KeywordTok{unique}\NormalTok{(d}\OperatorTok{$}\NormalTok{ag_dilution)))\}) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{# convert antigen dilution into antigen concentration in ng/ml}
\StringTok{  }\CommentTok{# keep only two variables: ag_conc and absorbance}
\StringTok{  }\KeywordTok{transmute}\NormalTok{(}\DataTypeTok{ag_conc =} \DecValTok{10}\OperatorTok{^}\DecValTok{6} \OperatorTok{/}\StringTok{ }\NormalTok{ag_dilution, absorbance)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] 1e+01 4e+01 1e+02 4e+02 1e+03 4e+03 1e+04 4e+04 1e+05 4e+05
## [11] 1e+06 4e+06
\end{verbatim}

As shown in Figure \ref{fig:elisa-std-1-raw}, if plotted directly, it can be observed that absorbance increases with increasing antigen concentration as expected, but the mathematical relationship is unclear and so the `optimal range' is also vague.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(std1, }\KeywordTok{aes}\NormalTok{(ag_conc, absorbance))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{'ELISA priliminary calibration curve'}\NormalTok{, }\DataTypeTok{x =} \StringTok{'antigen concentration (ng/ml)'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{2020-03-08-immunoassay-in-silico_files/figure-latex/elisa-std-1-raw-1} \caption{ELISA priliminary calibration curve}\label{fig:elisa-std-1-raw}
\end{figure}

However, as shown in Figure \ref{fig:elisa-std-1}, a linear relationship can be obtained by a double-log transformation. In this plot, it is clear that the useful range of antigen concentration would be \(1.0<\log_{10}{c}<{3.4}\), or \(10^1 < c < 10^{3.4}\), where \(c\) is the antigen concentration in \(ng/ml\). This corresponds to a range of dilution of \(4\times10^2 < x < 10^5\).

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(std1, }\KeywordTok{aes}\NormalTok{(}\KeywordTok{log10}\NormalTok{(ag_conc), }\KeywordTok{log10}\NormalTok{(absorbance)))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{'ELISA priliminary calibration curve (double log)'}\NormalTok{,}
       \DataTypeTok{x =} \StringTok{'log(antigen concentration (ng/ml))'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_abline}\NormalTok{(}\DataTypeTok{intercept =} \FloatTok{-3.4}\NormalTok{, }\DataTypeTok{slope =} \DecValTok{1}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_text}\NormalTok{(}\DataTypeTok{x=}\DecValTok{2}\NormalTok{,}\DataTypeTok{y=}\OperatorTok{-}\DecValTok{1}\NormalTok{, }\DataTypeTok{label=}\StringTok{'y = x - 3.4'}\NormalTok{, }\DataTypeTok{family=}\StringTok{"Helvetica"}\NormalTok{, }\DataTypeTok{size=}\FloatTok{4.5}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{2020-03-08-immunoassay-in-silico_files/figure-latex/elisa-std-1-1} \caption{ELISA priliminary calibration curve (double log)}\label{fig:elisa-std-1}
\end{figure}

Based on previous knowledge that the dilution should be in the range \(4\times10^2 < x < 10^5\), more experiments are carried out. The dilutions used are shown below.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{std2 <-}\StringTok{ }\KeywordTok{read_tsv}\NormalTok{(}\StringTok{'./2020-03-08-immunoassay-in-silico/elisa_std2.tsv'}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{janitor}\OperatorTok{::}\KeywordTok{clean_names}\NormalTok{() }\OperatorTok{%T>%}
\StringTok{  }\CommentTok{# print dilutions used}
\StringTok{  }\NormalTok{(}\ControlFlowTok{function}\NormalTok{(d)\{}\KeywordTok{print}\NormalTok{(}\KeywordTok{sort}\NormalTok{(}\KeywordTok{unique}\NormalTok{(d}\OperatorTok{$}\NormalTok{ag_dilution)))\}) }\OperatorTok{%>%}
\StringTok{  }\CommentTok{# convert antigen dilution into antigen concentration in ng/ml}
\StringTok{  }\CommentTok{# keep only two variables: ag_conc and absorbance}
\StringTok{  }\KeywordTok{transmute}\NormalTok{(}\DataTypeTok{ag_conc =} \DecValTok{10}\OperatorTok{^}\DecValTok{6} \OperatorTok{/}\StringTok{ }\NormalTok{ag_dilution, absorbance)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1]   800  1000  2000  4000  8000 10000 20000 32000 40000 64000
## [11] 80000
\end{verbatim}

The calibration curve is shown in Figure \ref{fig:elisa-std-fin}.

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{ggplot}\NormalTok{(std2, }\KeywordTok{aes}\NormalTok{(}\KeywordTok{log10}\NormalTok{(ag_conc), }\KeywordTok{log10}\NormalTok{(absorbance)))}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_point}\NormalTok{()}\OperatorTok{+}
\StringTok{  }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{'ELISA calibration curve'}\NormalTok{,}
       \DataTypeTok{x =} \StringTok{'log(antigen concentration (ng/ml))'}\NormalTok{)}\OperatorTok{+}
\StringTok{  }\KeywordTok{geom_smooth}\NormalTok{(}\DataTypeTok{method=}\StringTok{'lm'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{2020-03-08-immunoassay-in-silico_files/figure-latex/elisa-std-fin-1} \caption{ELISA calibration curve (double log)}\label{fig:elisa-std-fin}
\end{figure}

\hypertarget{q19}{%
\subsubsection*{Q19}\label{q19}}
\addcontentsline{toc}{subsubsection}{Q19}

\textbf{Briefly comment on the graph:}

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{summary}\NormalTok{(}\KeywordTok{lm}\NormalTok{(}\KeywordTok{log10}\NormalTok{(std2}\OperatorTok{$}\NormalTok{absorbance) }\OperatorTok{~}\StringTok{ }\KeywordTok{log10}\NormalTok{(std2}\OperatorTok{$}\NormalTok{ag_conc)))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = log10(std2$absorbance) ~ log10(std2$ag_conc))
## 
## Residuals:
##      Min       1Q   Median       3Q      Max 
## -0.09315 -0.03981  0.00023  0.04625  0.08439 
## 
## Coefficients:
##                      Estimate Std. Error t value Pr(>|t|)    
## (Intercept)         -3.397722   0.015712  -216.3   <2e-16 ***
## log10(std2$ag_conc)  0.996370   0.007425   134.2   <2e-16 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.04711 on 94 degrees of freedom
## Multiple R-squared:  0.9948, Adjusted R-squared:  0.9948 
## F-statistic: 1.801e+04 on 1 and 94 DF,  p-value: < 2.2e-16
\end{verbatim}

As shown in Figure \ref{fig:elisa-std-fin} and in the linear model summary above, when the antigen concentration is in the range \(10^1 < c < 2.5\times10^3\) (i.e.~the absorbance is in the range \(0.004 < A < 1.000\)), there is a significant correlation between the antigen concentration and the absorbance, which can be described by this equation:

\[\log_{10}{A} = \log_{10}{c} - 3.40\]

where \(A\) is the absorbance and \(c\) is the antigen concentration in \(ng/ml\).

As shown in Figure \ref{fig:elisa-std-fin}, when log(antigen concentration) is less than 1.7, the variation within each sets of absorbance readings is slightly larger, so the optimal range should be narrow down to \(10^{1.7} < c < 10^{3.4}\) for antigen concentration, or \(0.020 < A < 1.000\) for absorbance.

\hypertarget{c-measuring-concentration-of-the-unknown}{%
\subsection*{(c) Measuring concentration of the unknown}\label{c-measuring-concentration-of-the-unknown}}
\addcontentsline{toc}{subsection}{(c) Measuring concentration of the unknown}

\hypertarget{q20}{%
\subsubsection*{Q20}\label{q20}}
\addcontentsline{toc}{subsubsection}{Q20}

\textbf{Using appropriate dilutions and number of replicates (discuss briefly below). Calculate the concentration of antigen in the original (unknown) solution, stating your calculation process. Where relevant, you can append titled data sets to the end of this document. Esnure your answer is statistically valid (think back to the stats test used in RiaLab)}

First, I used a broad range of dilutions (again, \(1\times10^n\) and \(4\times10^n\) for \(n\) in \(\{1,2,3,4,5,6\}\)).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{df <-}\StringTok{ }\KeywordTok{read_tsv}\NormalTok{(}\StringTok{'./2020-03-08-immunoassay-in-silico/elisa_exp1.tsv'}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{janitor}\OperatorTok{::}\KeywordTok{clean_names}\NormalTok{() }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{transmute}\NormalTok{(}\DataTypeTok{ag_dilution =} \KeywordTok{factor}\NormalTok{(ag_dilution), absorbance)}
\KeywordTok{ggplot}\NormalTok{(df, }\KeywordTok{aes}\NormalTok{(ag_dilution, absorbance))}\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_boxplot}\NormalTok{()}\OperatorTok{+}
\StringTok{    }\KeywordTok{labs}\NormalTok{(}\DataTypeTok{title =} \StringTok{"ELISA Experiment for the Unknown"}\NormalTok{)}\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{1.000}\NormalTok{, }\DataTypeTok{color=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{size =} \FloatTok{0.6}\NormalTok{)}\OperatorTok{+}
\StringTok{    }\KeywordTok{geom_hline}\NormalTok{(}\DataTypeTok{yintercept =} \FloatTok{0.020}\NormalTok{, }\DataTypeTok{color=}\StringTok{'red'}\NormalTok{, }\DataTypeTok{size =} \FloatTok{0.6}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{2020-03-08-immunoassay-in-silico_files/figure-latex/elisa-exp1-1} \caption{Finding the appropriate dilution of the unknown so that the absorbance fall within the linear range.}\label{fig:elisa-exp1}
\end{figure}

\begin{Shaded}
\begin{Highlighting}[]
    \CommentTok{# scale_x_discrete(limits = rev(levels(df$ag_dilution)))+}
\end{Highlighting}
\end{Shaded}

As learnt from Q19, the linear range is where the absorbance lies between 0.020 and 1.000. According to Figure \ref{fig:elisa-exp1}, a \(10^3\) dilution would be the most appropriate. Therefore, I repeat 480 times with this dilution.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{elisa_absorbance <-}\StringTok{ }\KeywordTok{read_tsv}\NormalTok{(}\StringTok{'./2020-03-08-immunoassay-in-silico/elisa_exp_fin.tsv'}\NormalTok{) }\OperatorTok{%>%}
\StringTok{  }\NormalTok{janitor}\OperatorTok{::}\KeywordTok{clean_names}\NormalTok{() }\OperatorTok{%>%}
\StringTok{  }\KeywordTok{extract2}\NormalTok{(}\StringTok{'absorbance'}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

Curiously, again, the distribution is bimodal (the data is shown in Section \ref{elisa-absorbance}:

\begin{Shaded}
\begin{Highlighting}[]
\KeywordTok{qplot}\NormalTok{(elisa_absorbance, }\DataTypeTok{geom =} \StringTok{'histogram'}\NormalTok{, }\DataTypeTok{bins =} \KeywordTok{I}\NormalTok{(}\DecValTok{40}\NormalTok{), }\DataTypeTok{fill=}\KeywordTok{I}\NormalTok{(}\StringTok{'white'}\NormalTok{), }\DataTypeTok{color=}\KeywordTok{I}\NormalTok{(}\StringTok{'black'}\NormalTok{),}
      \DataTypeTok{main =} \StringTok{"distribution of 480 absorbance readings for the unknown"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{figure}
\includegraphics[width=1\linewidth]{2020-03-08-immunoassay-in-silico_files/figure-latex/elisa-abs-dist-1} \caption{Distribution of 480 absorbance readings for the ELISA assay with 1:1000 unknown sample and 1:40000 antibody}\label{fig:elisa-abs-dist}
\end{figure}

If I had to assume it's a normal distribution, a 95\% confidence interval could be calculated:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{conc <-}\StringTok{ }\DecValTok{10}\OperatorTok{^}\NormalTok{(}\KeywordTok{log10}\NormalTok{(elisa_absorbance) }\OperatorTok{+}\StringTok{ }\FloatTok{3.40}\NormalTok{) }\OperatorTok{*}
\StringTok{                }\DecValTok{10}\OperatorTok{^}\DecValTok{3} \OperatorTok{/}\StringTok{ }\CommentTok{# dilution}
\StringTok{                }\DecValTok{10}\OperatorTok{^}\DecValTok{6} \CommentTok{# ng/ml to mg/ml}
\NormalTok{mean <-}\StringTok{ }\KeywordTok{mean}\NormalTok{(conc); sd =}\StringTok{ }\KeywordTok{sd}\NormalTok{(conc);}
\NormalTok{t <-}\StringTok{ }\KeywordTok{qt}\NormalTok{(}\FloatTok{0.975}\NormalTok{, }\KeywordTok{length}\NormalTok{(conc)}\OperatorTok{-}\DecValTok{1}\NormalTok{); t_sd <-}\StringTok{ }\NormalTok{t}\OperatorTok{*}\NormalTok{sd}
\KeywordTok{c}\NormalTok{(}\DataTypeTok{mean=}\NormalTok{mean, }\DataTypeTok{sd =}\NormalTok{ sd, }\DataTypeTok{t =}\NormalTok{ t, }\DataTypeTok{t_sd =}\NormalTok{ t_sd, }\DataTypeTok{lower =}\NormalTok{ mean}\OperatorTok{-}\NormalTok{t_sd, }\DataTypeTok{upper =}\NormalTok{ mean}\OperatorTok{+}\NormalTok{t_sd)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       mean         sd          t       t_sd      lower      upper 
## 0.80949203 0.08313395 1.96492886 0.16335230 0.64613973 0.97284433
\end{verbatim}

(Used the relationship between antigen concentration and absorbance established previously: \(\log_{10}{A} = \log_{10}{c} - 3.40\))

The mean is 0.8095 mg/ml and the confidence interval is \(0.8094\0.1634\), or {[}0.6461 0.9728{]} mg/ml. (This is actually invalid because the distribution was not normal).

\hypertarget{supporting-information}{%
\section{Supporting Information}\label{supporting-information}}

\hypertarget{ria}{%
\subsection{RIA}\label{ria}}

The 276 counts for \(1\mu\text{L}\) of \(1\times10^4\) dilution of antigen:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{unknown_test[[}\StringTok{'count'}\NormalTok{]]}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   [1] 20336 17947 20618 23919 23332 23224 21150 23007 23463 20596
##  [11] 25927 18685 20270 21910 20466 20162 19880 17502 20314 24646
##  [21] 20281 20151 18946 20346 23137 21715 20108 19858 23180 19445
##  [31] 18012 20477 23256 19782 23235 24407 23647 24320 20064 21291
##  [41] 19521 22735 19250 21573 23560 18631 25656 19337 19174 24016
##  [51] 19630 24136 20292 24005 17643 23365 19890 20629 24103 20173
##  [61] 25102 20933 19174 19065 23397 19880 22388 19174 23159 23658
##  [71] 22008 24787 22931 24309 24841 23484 23777 25048 20976 24700
##  [81] 20053 20629 20792 19565 19261 24527 18099 24516 23072 22279
##  [91] 21139 23745 21715 19782 19977 19923 24353 18609 23452 19000
## [101] 20336 19858 18968 23951 24744 23539 24418 23810 21009 19478
## [111] 23625 19152 25211 23202 22963 22844 20379 22409 25069 17730
## [121] 20846 23452 24646 25254 24722 18533 24429 19597 19532 24483
## [131] 22073 19521 19804 25493 19956 20889 18240 17806 19445 18577
## [141] 24168 19543 25395 23929 19912 24820 24060 18707 18881 20368
## [151] 19044 24114 23224 20640 23995 20227 24049 19348 23506 24679
## [161] 19152 20412 19413 23560 22442 23897 19814 23159 22399 19586
## [171] 22605 23473 23148 19337 20650 17969 23061 22789 25482 19749
## [181] 24537 23408 20564 18989 22127 19011 20596 19337 19022 19402
## [191] 20455 23169 22724 19966 20835 20216 23148 23951 19510 20650
## [201] 19206 24559 23647 19434 22073 19880 20705 19543 17849 23691
## [211] 23940 17686 20813 19250 22876 19521 23767 22225 25688 23734
## [221] 18826 20683 20694 20433 21573 19206 25004 23354 23332 24635
## [231] 22540 17914 22692 23017 22149 19652 24038 20900 24744 20346
## [241] 22681 20064 19717 19109 24331 19500 23235 19825 19152 19684
## [251] 19630 21421 23365 22822 20162 22073 23202 24505 24309 22062
## [261] 23799 19836 22963 24429 19293 23962 21204 23886 18685 24147
## [271] 20531 19901 19521 23734 20118 24125
\end{verbatim}

\hypertarget{elisa-absorbance}{%
\subsection{ELISA}\label{elisa-absorbance}}

The 480 absorbance readings:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{elisa_absorbance}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   [1] 0.354 0.343 0.355 0.279 0.268 0.303 0.348 0.358 0.283 0.358
##  [11] 0.277 0.378 0.290 0.290 0.304 0.284 0.355 0.331 0.345 0.271
##  [21] 0.276 0.356 0.349 0.301 0.259 0.308 0.331 0.357 0.284 0.361
##  [31] 0.295 0.332 0.282 0.381 0.278 0.340 0.358 0.316 0.273 0.285
##  [41] 0.359 0.366 0.286 0.297 0.275 0.307 0.368 0.351 0.341 0.339
##  [51] 0.313 0.354 0.346 0.284 0.334 0.278 0.300 0.286 0.312 0.353
##  [61] 0.361 0.364 0.357 0.372 0.285 0.358 0.274 0.282 0.280 0.344
##  [71] 0.253 0.300 0.336 0.300 0.301 0.348 0.355 0.374 0.276 0.290
##  [81] 0.279 0.370 0.338 0.270 0.373 0.351 0.356 0.353 0.256 0.294
##  [91] 0.339 0.315 0.351 0.288 0.311 0.352 0.352 0.280 0.333 0.368
## [101] 0.334 0.294 0.297 0.299 0.279 0.343 0.357 0.309 0.366 0.363
## [111] 0.310 0.311 0.358 0.335 0.361 0.296 0.257 0.334 0.308 0.293
## [121] 0.293 0.336 0.342 0.352 0.366 0.287 0.266 0.286 0.360 0.313
## [131] 0.358 0.287 0.305 0.363 0.343 0.284 0.290 0.339 0.268 0.350
## [141] 0.363 0.334 0.343 0.271 0.324 0.299 0.258 0.334 0.309 0.336
## [151] 0.374 0.362 0.290 0.344 0.303 0.352 0.295 0.314 0.286 0.300
## [161] 0.287 0.292 0.369 0.349 0.292 0.349 0.360 0.334 0.339 0.277
## [171] 0.286 0.347 0.293 0.325 0.288 0.278 0.303 0.271 0.289 0.305
## [181] 0.309 0.364 0.344 0.309 0.355 0.360 0.298 0.298 0.299 0.322
## [191] 0.340 0.364 0.344 0.337 0.311 0.344 0.294 0.365 0.351 0.297
## [201] 0.384 0.327 0.350 0.315 0.326 0.301 0.316 0.292 0.300 0.366
## [211] 0.346 0.329 0.291 0.355 0.290 0.300 0.301 0.370 0.299 0.340
## [221] 0.336 0.274 0.301 0.359 0.342 0.345 0.350 0.356 0.347 0.317
## [231] 0.354 0.286 0.339 0.358 0.326 0.362 0.358 0.349 0.329 0.298
## [241] 0.317 0.337 0.327 0.309 0.301 0.291 0.368 0.342 0.359 0.347
## [251] 0.337 0.352 0.292 0.294 0.370 0.377 0.287 0.292 0.279 0.349
## [261] 0.315 0.370 0.365 0.280 0.352 0.342 0.342 0.363 0.278 0.335
## [271] 0.372 0.351 0.354 0.348 0.292 0.293 0.298 0.327 0.286 0.374
## [281] 0.335 0.348 0.359 0.274 0.314 0.354 0.359 0.347 0.331 0.345
## [291] 0.371 0.283 0.370 0.289 0.359 0.344 0.356 0.374 0.267 0.356
## [301] 0.304 0.333 0.279 0.344 0.355 0.366 0.291 0.306 0.352 0.361
## [311] 0.372 0.270 0.359 0.317 0.294 0.340 0.257 0.265 0.283 0.285
## [321] 0.293 0.330 0.345 0.322 0.294 0.336 0.362 0.369 0.343 0.283
## [331] 0.324 0.326 0.341 0.299 0.362 0.368 0.358 0.334 0.283 0.331
## [341] 0.278 0.261 0.351 0.337 0.288 0.278 0.269 0.298 0.361 0.311
## [351] 0.355 0.361 0.287 0.343 0.267 0.294 0.343 0.293 0.286 0.312
## [361] 0.296 0.340 0.267 0.281 0.301 0.326 0.356 0.287 0.265 0.296
## [371] 0.295 0.254 0.289 0.371 0.274 0.285 0.349 0.361 0.353 0.277
## [381] 0.341 0.332 0.336 0.296 0.274 0.321 0.279 0.297 0.346 0.273
## [391] 0.370 0.298 0.380 0.273 0.338 0.342 0.369 0.308 0.361 0.294
## [401] 0.312 0.353 0.371 0.288 0.354 0.278 0.367 0.280 0.315 0.335
## [411] 0.334 0.369 0.308 0.292 0.369 0.349 0.312 0.286 0.289 0.379
## [421] 0.349 0.315 0.339 0.297 0.355 0.310 0.287 0.342 0.296 0.275
## [431] 0.337 0.353 0.329 0.302 0.332 0.356 0.311 0.344 0.283 0.358
## [441] 0.288 0.332 0.341 0.278 0.367 0.284 0.287 0.321 0.343 0.286
## [451] 0.307 0.271 0.311 0.266 0.357 0.348 0.298 0.297 0.361 0.370
## [461] 0.377 0.362 0.330 0.388 0.287 0.332 0.295 0.357 0.279 0.306
## [471] 0.313 0.355 0.279 0.303 0.328 0.334 0.339 0.335 0.312 0.305
\end{verbatim}

\end{document}
